version: 2

sources:
  - name: staging
    database: innate-tempo-413618
    schema: ny_taxi_data
    
    tables:
      - name: external_fhv_trip_data


models:
  - name: stg_external_fhv_trip_data
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: dispatching_base_num
        data_type: string
        description: ""

      - name: affiliated_base_number
        data_type: string
        description: ""

      - name: sr_flag
        data_type: int64
        description: ""

      - name: pickup_locationid
        data_type: int64
        description: ""
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity: warn
    
      - name: dropoff_locationid
        data_type: int64
        description: ""
        tests:
          - relationships:
              field: locationid
              to: ref('taxi_zone_lookup')
              severity: warn

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""