version: 2

models:
  - name: dim_zones
    description: >
     List of unique zones identified by locationiid.
     Includes the service zone they correspond to (Green or Yellow).
  - name: fact_trips
    description: >
      Taxi trips corresponding to both service zones (Green and Yellow).
      The table contains records where both pickup and dropoff locations are valid and known zones.
      Each record corresponds to a trip uniquely identified by tripid.
    columns:
      - name: tripid
        data_type: string
        description: ""

      - name: dispatching_base_num
        data_type: string
        description: ""

      - name: service_type
        data_type: string
        description: ""

      # - name: sr_flag
      #   data_type: int64
      #   description: ""
        
      - name: pickup_locationid
        data_type: int64
        description: ""

      - name: pickup_borough
        data_type: string
        description: ""

      - name: pickup_zone
        data_type: string
        description: ""

      - name: dropoff_locationid
        data_type: int64
        description: ""

      - name: dropoff_borough
        data_type: string
        description: ""

      - name: dropoff_zone
        data_type: string
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""